/**
 * Validator Smoke 3 — Auto-generated by foundry
 * Minimal extension smoke test after validator fix
 * Generated: 2026-03-20T18:21:14.332Z
 */

import type { ClawdbotPluginApi } from "clawdbot/plugin-sdk";

export default {
  id: "validator-smoke-3",
  name: "Validator Smoke 3",
  description: "Minimal extension smoke test after validator fix",

  register(api: ClawdbotPluginApi) {
    const logger = api.logger;

    api.registerTool({
      name: "ping",
      label: "Ping",
      description: "returns pong",
      parameters: {
        type: "object",
        properties: {

        },
        required: [],
      },
      async execute(_toolCallId: string, params: unknown) {
        const p = params as any;
        return { ok: true, pong: true };
      },
    });




    logger.info("[validator-smoke-3] Extension loaded");
  },
};
