#!/usr/bin/env node
/**
 * Clawd Memory - Weekly Digest Generator
 * Generates weekly summary of work, projects, and priorities
 */

const fs = require('fs');
const path = require('path');

const MEMORY_DIR = process.env.MEMORY_DIR || '/root/.openclaw/workspace/memory';
const DIGEST_DIR = path.join(MEMORY_DIR, 'digest');
const STATE_FILE = path.join(MEMORY_DIR, 'clawd-memory-state.json');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function getToday() {
  return new Date().toISOString().split('T')[0];
}

function getWeekStart() {
  const d = new Date();
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  return new Date(d.setDate(diff)).toISOString().split('T')[0];
}

function loadState() {
  if (fs.existsSync(STATE_FILE)) {
    return JSON.parse(fs.readFileSync(STATE_FILE, 'utf8'));
  }
  return { projects: [], created: getToday() };
}

function generateDigest() {
  ensureDir(DIGEST_DIR);
  
  const state = loadState();
  const weekStart = getWeekStart();
  const today = getToday();
  
  const activeProjects = state.projects.filter(p => p.status === 'active');
  const completedThisWeek = state.projects.filter(p => {
    if (p.status !== 'completed') return false;
    // Check if completed this week (simplified)
    return true;
  });
  const staleProjects = state.projects.filter(p => {
    const updated = new Date(p.updated);
    const daysStale = Math.floor((new Date() - updated) / (1000 * 60 * 60 * 24));
    return daysStale > 7 && p.status === 'active';
  });
  
  const digest = `# Weekly Digest - Week of ${weekStart}

**Generated:** ${today}

---

## 📊 Overview

- **Active Projects:** ${activeProjects.length}
- **Completed This Week:** ${completedThisWeek.length}
- **Stale Projects (7+ days):** ${staleProjects.length}

---

## 🚀 Active Projects

${activeProjects.length > 0 ? activeProjects.map(p => 
  `- **${p.name}** (${p.priority})\n  - Last updated: ${p.updated}\n  - Status: ${p.status}`
).join('\n\n') : 'No active projects tracked.'}

---

## ⚠️ Stale Projects (Need Attention)

${staleProjects.length > 0 ? staleProjects.map(p => 
  `- **${p.name}** - ${Math.floor((new Date() - new Date(p.updated)) / (1000 * 60 * 60 * 24))} days since update`
).join('\n') : 'No stale projects. Great job!'}

---

## ✅ Completed This Week

${completedThisWeek.length > 0 ? completedThisWeek.map(p => 
  `- **${p.name}**`
).join('\n') : 'No completions recorded this week.'}

---

## 🎯 Recommended Focus

${staleProjects.length > 0 ? 
  `1. Address stale projects: ${staleProjects.slice(0, 3).map(p => p.name).join(', ')}\n` +
  `2. Review active project priorities\n` +
  `3. Archive completed work`
  : 
  `1. Continue active project momentum\n` +
  `2. Review for process improvements\n` +
  `3. Plan next week's priorities`
}

---

## 📝 Notes & Observations

*[Add any observations about processes, pain points, or improvements needed]*

---
*Generated by Clawd Memory System*
`;

  const digestFile = path.join(DIGEST_DIR, `digest-${weekStart}.md`);
  fs.writeFileSync(digestFile, digest);
  
  // Update state
  state.lastDigest = today;
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
  
  return {
    generated: true,
    path: digestFile,
    weekStart,
    summary: {
      active: activeProjects.length,
      stale: staleProjects.length,
      completed: completedThisWeek.length
    }
  };
}

// CLI usage
if (require.main === module) {
  const result = generateDigest();
  console.log(JSON.stringify(result, null, 2));
}

module.exports = { generateDigest };
